<a href="https://colab.research.google.com/github/SeungYeon2000/pytorch/blob/main/Chapter3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter3 - Contents


1.   Understanding Tensors(basic data structure)
2.   Indexing and operating on tensors
3.   Interoperating with NumPy multidimensional arrays
4.   Moving computations to the GPU for speed



# 3.1 The world as floating-point numbers

how Pytorch handles and stores data?

fundamental data structure : the tensor

tensor : 임의 차원의 수로 벡터와 행렬의 일반화를 가리킴

dimensionality of a tensor = tensor내 scalar값을 지칭하는 데 사용된 index의 개수(n차원의 data -> n개의 indices)

NumPy : 가장 인기 있는 multidimensional array library

# Tensors : Multidimensional arrays
A tensor = An array
숫자들 모음을 저장하는 data 구조 (index를 사용하는 접근가능한 것, 다중 인덱스로 인덱싱 될 수 있는 것)

In [1]:
#In[1] :
a = [1.0, 2.0, 1.0]

In [2]:
#In[2] :
a[0]

1.0

In [3]:
#In[3]:
a[2]=3.0
a
# index 번호에 직접 대입해줘서 변경 가능

[1.0, 2.0, 3.0]

In [5]:
#In[4]:
import torch   #import the torch module
a=torch.ones(3)  #creates 1D 1로 이루어진 size3 tensor
a

tensor([1., 1., 1.])

In [6]:
#In[5]:
a[1]

tensor(1.)

In [7]:
#In[6]:
float(a[1])

1.0

In [8]:
#In[7]:
a[2]=2.0
a

tensor([1., 1., 2.])

In [10]:
#in[8]:  
points = torch.zeros(6)   #.zeros를 이용하는 것은 적절한 size의 array를 얻기 위함임.
points[0] = 4.0    # 우리가 실제로 원하는 값으로 zero를 대체함.
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0
# python list를 사용하는 대신 torch/array를 사용하는 방법
points

tensor([4., 1., 5., 3., 2., 1.])

In [11]:
#In[9]:
points=torch.tensor([4.0,1.0,5.0,3.0,2.0,1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [12]:
#In[10]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [14]:
#In[11]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [15]:
#In[12]:
points.shape

torch.Size([3, 2])

In [16]:
#In[13]:
points=torch.zeros(3,2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [18]:
#In[14]:
points=torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [19]:
#In[15]:
points[0,1]

tensor(1.)

In [20]:
#In[16]:
points[0]

tensor([4., 1.])

# 3.3 Indexing Tensors

obtaining a tensor containing all points but the first -> easy :)


In [21]:
#In[53]:
some_list = list(range(6)) 
some_list[:]
some_list[1:4]  #1부터3
some_list[1:]   #1부터마지막전
some_list[:4]   #처음부터4전
some_list[:-1]  #처음부터마지막에서하나전
some_list[1:4:2]  #1,3

[1, 3]

In [22]:
#In[54]:
points[1:]
points[1:, :]
points[1:, 0]
points[None]

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

# Ex1
Create a tensor a from list(range(9)) size offset stride 체크


In [9]:
import torch
a=torch.tensor(range(0,9))
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
b=a.view(3,3)
b

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

view function은 주어진 array를 (row개수,column개수)로 나눈다

In [12]:
c=torch.tensor
c = b[1:,1:]
c

tensor([[4, 5],
        [7, 8]])

# 2. Pick a mathematical operation like cosine or square root. Can you find a corresponding function in the torch library
a. Apply the function element-wise to a. Why does it return an error?

b. What operation is required to make the function work?

c. Is there a version of your function that operates in place?

-> googling해서 찾음!